### ISSUE TITLE
App and app data fail to restore on Pie

### ISSUE THREAD

**Issue by Madis0** [jensstein/oandbackup#233]
Backed up on Android 8.1, attempting to restore on 9.0. Here's what happens:
```
KDE Connect: avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0
KDE Connect: System server has no access to read file context u:object_r:sdcardfs:s0 (from path /storage/emulated/0/Download/oandbackups/org.kde.kdeconnect_tp/base.apk, context u:r:system_server:s0)
KDE Connect: Error: Unable to open file: /storage/emulated/0/Download/oandbackups/org.kde.kdeconnect_tp/base.apk
KDE Connect: Consider using a file under /data/local/tmp/
KDE Connect: Error: Can't open file: /storage/emulated/0/Download/oandbackups/org.kde.kdeconnect_tp/base.apk
KDE Connect: 
KDE Connect: Exception occurred while executing:
KDE Connect: java.lang.IllegalArgumentException: Error: Can't open file: /storage/emulated/0/Download/oandbackups/org.kde.kdeconnect_tp/base.apk
KDE Connect: 	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:328)
KDE Connect: 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:906)
KDE Connect: 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
KDE Connect: 	at android.os.ShellCommand.exec(ShellCommand.java:103)
KDE Connect: 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21440)
KDE Connect: 	at android.os.Binder.shellCommand(Binder.java:634)
KDE Connect: 	at android.os.Binder.onTransact(Binder.java:532)
KDE Connect: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
KDE Connect: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3901)
KDE Connect: 	at android.os.Binder.execTransact(Binder.java:731)
org.kde.kdeconnect_tp: cannot restore data without restoring apk, package is not installed
```

This happens for all apps, not specifically this one.

Initially I tried the default folder: batch restore app+data, single restore app+data, single restore app. At least the APKs are manually installable, therefore not corrupt. 

Then I tried moving the folder to Downloads, did not succeed. 
**Restoring apps did succeed, however, when moving the folder to `/data/local/tmp/`, as the error suggested. App data is still lost, oh well.**

**Comment by jensstein** [comment]
0.3.5 released :)

**Comment by Madis0** [comment]
Confirmed to successfully back up and restore user apps with data on Android Pie.
