### ISSUE TITLE
Crash on restore

### ISSUE THREAD

**Issue by ildar** [jensstein/oandbackup#75]
I cought a crash (reproducible) when restoring from tmpfs folder. I.e. I have tmpfs FS mounted to /sdcard/tmp and see the crash:
> Thu, 18 Dec 2014 14:09:32 +0600: W/dalvikvm( 1990): threadid=11: thread exiting with uncaught exception (group=0x40bdb930)
> Thu, 18 Dec 2014 14:09:32 +0600: E/AndroidRuntime( 1990): FATAL EXCEPTION: Thread-194
> Thu, 18 Dec 2014 14:09:32 +0600: E/AndroidRuntime( 1990): java.lang.NullPointerException
> Thu, 18 Dec 2014 14:09:32 +0600: E/AndroidRuntime( 1990): 	at dk.jens.backup.ShellCommands.doRestore(ShellCommands.java:132)
> Thu, 18 Dec 2014 14:09:32 +0600: E/AndroidRuntime( 1990): 	at dk.jens.backup.OAndBackup$3.run(OAndBackup.java:284)
> Thu, 18 Dec 2014 14:09:32 +0600: E/AndroidRuntime( 1990): 	at java.lang.Thread.run(Thread.java:856)
> Thu, 18 Dec 2014 14:09:32 +0600: W/ActivityManager(  413):   Force finishing activity dk.jens.backup/.OAndBackup
...
> Thu, 18 Dec 2014 14:09:33 +0600: E/WindowManager( 1990): Activity dk.jens.backup.OAndBackup has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{418ecf28 V.E..... R.....ID 0,0-580,162} that was originally added here

This is on CM10.1

**Comment by ildar** [comment]
Tried both debug and normal F-Droid versions (0.2.9). No crashes anymore.
I tested with the same backup data.
Not sure why it didn't crash, maybe it's Factory Reset I did (ROM is the
same).
Sorry. Closing.
