### ISSUE TITLE
oandbackup crashes on start on Android 5.0.2

### ISSUE THREAD

**Issue by lightonflux** [jensstein/oandbackup#82]
So i updated to a beta of CyanogenMod 12 which is Android 5.0.2.

oab crashes immediately if i try to start it on CM12. 

There is no crash log. :(

**Comment by aelmahmoudy** [comment]
Same for OMNI 5.0.2, here's the error from logcat:
```E/AndroidRuntime( 4250): FATAL EXCEPTION: Thread-207
E/AndroidRuntime( 4250): Process: dk.jens.backup, PID: 4250
E/AndroidRuntime( 4250): java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
E/AndroidRuntime( 4250): 	at dk.jens.backup.AppInfoHelper.getPackageInfo(AppInfoHelper.java:48)
E/AndroidRuntime( 4250): 	at dk.jens.backup.OAndBackup$1.run(OAndBackup.java:105)
E/AndroidRuntime( 4250): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 2432):   Force finishing activity dk.jens.backup/.OAndBackup
D/OpenGLRenderer( 2432): Render dirty regions requested: true
D/Atlas   ( 2432): Validating map...
I/OpenGLRenderer( 2432): Initialized EGL, version 1.4
D/OpenGLRenderer( 2432): Enabling debug mode 0
E/WindowManager( 4250): 
E/WindowManager( 4250): android.view.WindowLeaked: Activity dk.jens.backup.OAndBackup has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{2d20413 V.E..... R......D 0,0-684,232} that was originally added here
E/WindowManager( 4250): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
E/WindowManager( 4250): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
E/WindowManager( 4250): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager( 4250): 	at android.app.Dialog.show(Dialog.java:298)
E/WindowManager( 4250): 	at android.app.ProgressDialog.show(ProgressDialog.java:116)
E/WindowManager( 4250): 	at android.app.ProgressDialog.show(ProgressDialog.java:104)
E/WindowManager( 4250): 	at dk.jens.backup.HandleMessages$ProgressHandler.handleMessage(HandleMessages.java:96)
E/WindowManager( 4250): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager( 4250): 	at android.os.Looper.loop(Looper.java:135)
E/WindowManager( 4250): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/WindowManager( 4250): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager( 4250): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/WindowManager( 4250): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/WindowManager( 4250): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by jensstein** [comment]
thanks for reporting.
the crash has already been reported and fixed: https://github.com/jensstein/oandbackup/issues/73
that issue also has an apk you can use until the next release, which i think will be in the beginning of next week.
